### ISSUE TITLE
[Feature Request] Get custom colors

### ISSUE THREAD

**Issue by Jared0430** [opl-/beatsaber-http-status#27]
It would be great if we could get the player chosen colors either in the status object, or better yet when the song starts with the colors for that level (taking into account the environment)

**Comment by Pixel-Therapy** [comment]
I wanted to ask the same

**Comment by LeoDJ** [comment]
Yes, this would be greatly appreciated. I'm currently in the process of writing a Beatsaber lightings events to LED lighting bridge and not having custom colors really limits the functionality ^^'

**Comment by Protected** [comment]
Came here to ask for this, surprised it has such an old ticket. This would be very useful in the StatusObject.

**Comment by codingcatgirl** [comment]
Looking for this as well! Including the custom colors if they have been overridden by a map using Chromapper etc… https://bsmg.wiki/mapping/basic-lighting.html#map-color-overrides

**Comment by opl-** [comment]
Added in f093556fe50e4ec5d4470a2213033b2431f08a4c, released in v1.18.0. Also works with SongCore color overrides.

**Comment by codingcatgirl** [comment]
Holy shit, thanks!

Isn't there also something that allows overwriting the colors of single notes? I might be mistaken. It could be interesting to just put the custom_json_data stuff directly in the websocket output :)

**Comment by opl-** [comment]
While implementing this I had a friend mention as a joke that putting it as part of `beatmap` should be fine unless some mod allows going through all the colors of a rainbow. I hate that this joke turned out to be a reality. Completely forgot about Chroma.

I'll just say that for now the way the mod is written and the protocol designed makes it difficult to allow optional mods and extra data to be sent out over the WebSocket while keeping it reasonably clean and easy to use.

I'm not entirely opposed to exposing `_customData` as it would certainly be useful, especially for tinkering. I'll think about whether this is a good idea and if there's a decent solution for the changing environment colors problem.

**Comment by codingcatgirl** [comment]
Okay, no hurry! Thanks for your work so far <3

**Comment by Protected** [comment]
Ooo, now I have to actually make the widget I wanted. I'll let you know when I have a link for the list.

**Comment by codingcatgirl** [comment]
Since i'm just tinkering with this again, i felt like i might comment on here that this is still an open issue. Could be worth reopening it ^^
