### ISSUE TITLE
Database recording function added version

### ISSUE THREAD

**Issue by rynan4818** [opl-/beatsaber-http-status#38]
Hi, I introduced it the other day in a pull request, but it's finally ready to be published on GitHub.
I've modded http-status to create a tool that stores game play information in a SQLite database.

https://github.com/rynan4818/beatsaber-http-status-db

We also created a tool that uses the recorded database to automatically isolate gameplay videos recorded in OBS Studio and others.

https://github.com/rynan4818/bs-movie-cut

I'm using a translation tool for English, so please bear with me if there are any quirks.
The documentation is in Japanese only.

**Comment by opl-** [comment]
Admittedly I'm not sure how to approach this one. I don't really know Japanese, but from what I could understand it's a fork of the mod that saves data in an SQLite database, which then can be read by bs-movie-cut in order to splice recordings of your gameplay by song.

It looks like a really neat tool, but at the same time it goes against the intended way of using this mod. The idea is that you connect through the WebSocket with a third party program and then use the data sent through that. This is done in an attempt to avoid having to update things like your mod on every game update.

By making a fork you're forcing users to install a different version of this mod to use your software. If another fork comes out, suddenly people would have to install 2 versions of the same mod, which is just asking for trouble.

There's also the issue of all the documentation and the software itself being in Japanese, which I'd assume many users will have problems understanding. This is especially important due to a fork of the mod being required to use it, unlike all the other things on the wiki list.

**Comment by rynan4818** [comment]
I understand very well what you are saying.
I also initially created the following program to connect via WebSocket and save it to the SQLite database.

https://github.com/rynan4818/movie-cut-record

However, the idea was that you would have to launch the program every time you played the game, and you would forget to launch the program.
In addition, I felt that it would be wasteful to go through the trouble of communicating via WebSocket in order to record to the SQLite database.
Therefore, it was thought from the beginning that it would be best to create the program as a mod, considering the user's convenience.

However, that is an unintended use of HTTP Status, and every time HTTP Status is updated, my mod also needs to be updated.
It's a burden on me to keep updating mods, and it's a nuisance to users when they stop updating.
I had a lot of trouble, but in the end, I decided to modify the HTTP Status for convenience.

I hadn't even thought about the competing issues that would arise if other similar forks occurred. I am sorry for this point.

I understand that the problem is that the documentation and source code comments are only in Japanese.
However, I don't have the ability to write in English due to my lack of study, so I have to rely on Google Translate, etc.
It will be at a level of English that is not much different from translating it on the web in real time.
However, since it is difficult for people who do not understand Japanese to use it, it is difficult to create all the documents in English, but I would like to consider writing both Japanese and English at least in the GitHub README.

Now that I understand that there are problems with the tools I've created, I'll take them into consideration as I update them in the future.
