### ISSUE TITLE
Events obstacleEnter & obstacleExit not triggered

### ISSUE THREAD

**Issue by ShiroSFX** [opl-/beatsaber-http-status#42]
Hello,

## Reproduction steps
I've an eventListener that capture each event in the game, but in-game when i enter a wall (and leave), none of these events are triggered.

I've already see the issue in a anterior version but that's fixed. #6 

## Environment
BeatSaber version: 1.9.1
HTTP Status version: 1.10.0
Platform: Steam BeatSaber with Oculus

**Comment by ErisApps** [comment]
@ShiroSFX Just wanted to let you know that I'm currently looking into the issue.
As far as my testing goes, it was caused by my own commit (5012c14cdfdad7e71cc40382483f64a8a30d6a19) to update the mod for BS 1.8.0 and the (back then) brand new BSIPA 4. Due to changes in the behaviour of BSIPA 4 itself, it seems that our method to detect this broke as a side-effect.

**Comment by opl-** [comment]
Eris accidentally introduced the issue, but I didn't catch it while reviewing their code. Eris was also the one who looked into it and figured out what the cause of this issue was, so credit where credit is due.

With this issue everything I wanted to get fixed before releasing a new version should be fixed, so expect a new release Soon™.

**Comment by ShiroSFX** [comment]
Hello,

I don't know if you work for the 1.16.2 version, but ObstacleEnter & Exit don't work at this time :)

### Environment
BeatSaber version: 1.16.2
HTTP Status version: lastest
Platform: Steam BeatSaber with Index
