### ISSUE TITLE
Deprecated beatmap events link

### ISSUE THREAD

**Issue by TakingFire** [opl-/beatsaber-http-status#48]
The [current link](https://steamcommunity.com/sharedfiles/filedetails/?id=1377190061) to the beatmap events reference has moved to it own site.
However, there doesn't seem to be an accurate description there, either. [This](https://bsmg.wiki/mapping/basic-lighting.html#lighting-types) explains the different areas, but not the specific numbers and their types used in the json data.
Either a new link, or a direct explanation would be much appreciated :)

**Comment by nyanbre** [comment]
Here: https://github.com/Caeden117/ChroMapper/blob/master/Assets/__Scripts/Map/Events/MapEvent.cs

But yeah, it'll be good to update wiki.

**Comment by opl-** [comment]
Admittedly I had some issues finding good resources on it myself when exposing this data. I opted to simply export the literal values the game gets from the beatmap to be safe from any potential future updates introducing weird changes and in case a custom map were to interpret those differently. I took the same approach with documentation, where I tried to just link to the best resource I could find about it at the time instead of trying to document it myself.

I updated the documentation to point to both of the resources you guys mentioned here. Thank you for mentioning those resources!
