### ISSUE TITLE
Could this ever work on the oculus quest?

### ISSUE THREAD

**Issue by mandelmonkey** [opl-/beatsaber-http-status#65]
I am new to modding but is this 100% pc only or could it also work on the oculus quest version of beatsaber?
So another app on the device could get events over localhost

**Comment by jonathanhammond** [comment]
+1 for an Oculus Question version. 🙏

**Comment by mandelmonkey** [comment]
Oh interesting your saying the quest unity was not written in unity? Or the
android os is compiled it into c++?

**Comment by ErisApps** [comment]
Quest uses Unity as the underlying game engine as well, but the way mods are written for PC (including Oculus Link which is considered PCVR as well) and standalone Quest is vastly different from each other (it's like day and night of a difference if I have to use a figure of speech). Quest has been recompiled to C++ because [IL2CPP](https://docs.unity3d.com/Manual/IL2CPP.html) is enabled for that platform.
Other than that, Quest and PC both utilize vastly different modloaders as well so it's not just as simple as enabling a checkbox somewhere. 🙂
All those things happen to be one reason or another why mods have to be rewritten from scratch in order to run on standalone quest, or the other way around.

I hope that answers your questions?

**Comment by mandelmonkey** [comment]
Yes it does, thanks for explaining
