### ISSUE TITLE
1.18 Cover image for non-custom songs displays all cover images in one

### ISSUE THREAD

**Issue by peddermaster2** [opl-/beatsaber-http-status#82]
## Current behavior
Playing a Beat Saber / non-custom Song the cover image is huge image with all cover images.
![grafik](https://user-images.githubusercontent.com/1105042/142658847-c65a8d1b-e63d-4b51-bd76-38ef2c5eec0b.png)
![grafik](https://user-images.githubusercontent.com/1105042/142660143-8543c723-404d-4225-82ba-b252e346b4e6.png)

## Expected behavior
Only the cover image of the currently played song is displayed.

## Reproduction steps
Play any non-custom Beat Saber song.

## Environment

BeatSaber version: 1.18.3
HTTP Status version: 1.19.1 bs1.18.0 c7d6ab6b
Platform: Steam, Valve Index

**Comment by opl-** [comment]
Finally looked into this. It looks like the texture rectangle isn't exposed by Unity in the `Sprite` instance we get from Beat Saber's `GetCoverImageAsync`, so it's either stored somewhere by the game itself and I failed to notice it, or I'm just unable to access it through the `Sprite` getters for whatever reason. I'll give it another shot when I'm more awake.

**Comment by opl-** [comment]
After more investigation and some encouragement from Auros, I found out that `Sprite.uv` returns useful values which I missed because they were being rounded by the stringification when logging. For whatever reason `Sprite.textureRect` and `Sprite.rect` don't return valid values for the sprite position in the atlas.
